Adding UTs for Button Filled
litmuschaos/litmus-ui pull request #124
Opened 2021-10-28 11:06 UTC by S-ayanide

Signed-off-by: Sayan Mondal <sayan@chaosnative.com>

Adding Unit Test for Button Filled Component

2021-10-28 11:26 UTC, arkajyotiMukherjee requested changes

2021-10-28 11:26 UTC, arkajyotiMukherjee commented on src/core/Button/ButtonFilled/__tests__/ButtonFilled.test.tsx
> +  it("should be clickable", () => {
can you follow the UT approach outlined in the EditableText component or AutoCompleteChip component

2021-11-03 05:39 UTC, arkajyotiMukherjee requested changes

2021-11-03 05:39 UTC, arkajyotiMukherjee commented on src/core/Button/ButtonFilled/__tests__/ButtonFilled.test.tsx
> +  const Button = component;
This might be a bit redundant...as you can use the component variable directly... component will regenerate after each test so as to not carry any state in between the tests.

2021-11-03 06:01 UTC, S-ayanide commented on src/core/Button/ButtonFilled/__tests__/ButtonFilled.test.tsx
> +  const Button = component;
Right, this shouldn't be required only `component` shall do

2021-11-03 06:36 UTC, arkajyotiMukherjee approved these changes

2021-11-03 09:16 UTC, merged