Snackbar
litmuschaos/litmus-ui pull request #97
Opened 2021-07-05 07:21 UTC by vanshBhatia-A4k9

Added the Snackbar component

![Screenshot from 2021-07-05 12-50-50](https://user-images.githubusercontent.com/40641427/124432892-be6fec80-dd8f-11eb-8226-56c4e15d671d.png)
![Screenshot from 2021-07-05 12-50-59](https://user-images.githubusercontent.com/40641427/124432898-bfa11980-dd8f-11eb-92a9-e592e775b968.png)
![Screenshot from 2021-07-05 12-51-02](https://user-images.githubusercontent.com/40641427/124432899-c039b000-dd8f-11eb-8651-25fec9f889e5.png)

2021-07-05 07:34 UTC, whitetiger1399 commented on src/core/Snackbar/Snackbar.tsx
> +  variant?: Variant;
May you handle the styling for the case of `variant: undefined`. Either assign some styling as a fallback or make any of the existing options as default

2021-07-05 07:36 UTC, whitetiger1399 requested changes
Please check the variant prop for undefined case

2021-07-05 08:58 UTC, whitetiger1399 approved these changes
Awesome work!! Thanks a million

2021-07-05 11:16 UTC, arkajyotiMukherjee requested changes
Some testcases I feel is not actually testing the component...those can be removed @vanshBhatia-A4k9

2021-07-05 11:16 UTC, arkajyotiMukherjee commented on src/core/Snackbar/__tests__/Snackbar.test.tsx
> +  screen.getByText("est Snack", { exact: false }); // substring match
This test how is it helping

2021-07-05 11:16 UTC, arkajyotiMukherjee commented on src/core/Snackbar/__tests__/Snackbar.test.tsx
> +  screen.getByText(/sNaCkBaR/i); // substring match, ignore case
these as well...We should be only checking full string in the exact case as it is, right?

2021-07-05 11:16 UTC, arkajyotiMukherjee commented on src/core/Snackbar/__tests__/Snackbar.test.tsx
> +  screen.getByText((content, element) => content.startsWith("Test"));
same

2021-07-05 11:16 UTC, arkajyotiMukherjee commented on src/core/Snackbar/__tests__/Snackbar.test.tsx
> +        element?.tagName.toLowerCase() === "p" && content.startsWith("Test")
This is internal with Mui...do we need to check this

2021-07-05 11:16 UTC, arkajyotiMukherjee commented on src/core/Snackbar/__tests__/Snackbar.test.tsx
> +  screen.getByText("Test Snackbar"); // full string match
This test is good

2021-07-06 11:48 UTC, arkajyotiMukherjee approved these changes

2021-07-06 11:50 UTC, merged